[build]
  command = "composer install && php artisan optimize"
  publish = "public"

[build.environment]

  PHP_VERSION = "8.2"
  
  
  APP_DEBUG = "false"
  APP_URL = "https://umar-awan.netlify.app"
